name: Codacy Analysis CLI with Code Coverage

on: [push]

jobs:
  codacy-analysis-cli:
    name: Codacy Analysis CLI with Code Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.x'

      - name: Build
        run: dotnet build --no-restore

      - name: Test with Code Coverage
        run: dotnet test --collect:"XPlat Code Coverage"

      - name: Generate Reports
        run: |
          dotnet tool install --global dotnet-reportgenerator-globaltool
          reportgenerator "-reports:**/coverage.cobertura.xml" "-targetdir:coverage/reports" -reporttypes:Html

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage/reports
