name: .NET Core Desktop

on:
  push:
    branches: [ "test1" ]
  pull_request:
    branches: [ "test1" ]

jobs:
  build-and-test:
    strategy:
      matrix:
        configuration: [Debug, Release]
        dotnet-version: ['6.0.x']
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
        fetch-depth: 1

    - name: Cache .NET SDK and NuGet packages
      uses: actions/cache@v2
      with:
        path: ~/.nuget/packages
        key: nuget-${{ runner.os }}-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          nuget-
    - name: Install .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
        architecture: x64

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: src/settings-ui/Settings.UI.UnitTests/TestResults
