name: .NET Code Quality and Coverage

on:
  push:
    branches: ["johnny"]
  pull_request:
    branches: ["johnny"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.x' # Adjust the .NET version as per your project's requirement

    - name: Test with code coverage
      run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura

    - name: Publish Code Coverage
      uses: codecov/codecov-action@v2
      with:
        files: ./path/to/your/cobertura/coverage.cobertura.xml # Adjust this path to point to your cobertura coverage file
        fail_ci_if_error: true
