name: Simple C# Workflow

on:
  push:
    branches: [ johnny ]
  pull_request:
    branches: [ johnny ]

jobs:
  setup-environment:
    runs-on: windows-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    - name: Echo Success Message
      run: echo "Workflow completed successfully"
