name: .NET Code Quality and Coverage

on:
  push:
    branches: ["johnny"]
  pull_request:
    branches: ["johnny"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.x' # Adjust the .NET version as per your project's requirement

    - name: Test with code coverage
      run: echo "Test with code coverage"

    - name: Publish Code Coverage
      uses: codecov/codecov-action@v2
