name: Johnny .NET Core Workflow

on:
  push:
    branches: [ "johnny" ]
  pull_request:
    branches: [ "johnny" ]

jobs:
  setup-and-restore:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Display .NET Version
      run: dotnet --version
