name: Johnny .NET Core Workflow

on:
  push:
    branches: [ "johnny" ]
  pull_request:
    branches: [ "johnny" ]

jobs:
  setup-and-check:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    - name: List files in the repository
      run: ls -la

    - name: Display environment information
      run: echo "Running on ${{ runner.os }} with .NET version ${{ steps.setup-dotnet.outputs.dotnet-version }}"
