name: Code Coverage Analysis

on: [push]

jobs:
  code-coverage-analysis:
    name: Code Coverage Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@master
