name: CI

on:
  push:
    branches:
      - kkTest

jobs:
  build:
    name: Build PowerToys
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Build for x64
      uses: ./templates/build-powertoys-ci.yml
      with:
        platform: x64

    - name: Build for ARM64
      uses: ./templates/build-powertoys-ci.yml
      with:
        platform: arm64
