name: Check .NET Version

on:
  push:
    branches:
      - kkTest  

jobs:
  check-dotnet-version:
    name: Check .NET Version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.0  # Specify the minimum .NET version you want to check

      - name: Run .NET --version
        run: dotnet --version

      - name: Check .NET version
        run: |
          installed_version=$(dotnet --version)
          required_version="5.0"
          
          if [[ "$(printf '%s\n' "$required_version" "$installed_version" | sort -V | head -n 1)" == "$required_version" ]]; then
            echo "The .NET version is greater than or equal to 5.0."
          else
            echo "The .NET version is less than 5.0."
            exit 1
          fi
        working-directory: /installer
