name: Check .NET Version

on:
  push:
    branches:
      - kkTest  # Replace with your main branch name

jobs:
  check-dotnet-version:
    name: Check .NET Version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.*.*  # Specify the .NET version you want to check for

      - name: Run .NET --version
        run: dotnet --version

      - name: Check .NET version
        run: |
          if [[ $(dotnet --version) == "5.0"* ]]; then
            echo "The .NET version is 5.0."
          else
            echo "The .NET version is not 5.0."
            exit 1
          fi
        working-directory: /installer 
